# Sample workflow to access AWS resources when workflow is tied to branch

name: Tf Plan
on:
  workflow_dispatch:
  push: # This allows workflow to be run on-demand
    branches: 
      - main 
        # push:
        #branches:
        #- master

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          role-to-assume: 
          role-session-name: rolesession
          aws-region: ap-southeast-2
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false   # need this for outputs to work

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true 

      - name: Terraform Validate
        id: validate
        run: terraform validate 
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true 
